//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedDb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientFile()
        {
            this.PatientHistories = new HashSet<PatientHistory>();
        }
    
        public int ID { get; set; }
        public int TenantID { get; set; }
        public int PatientID { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Tenant Tenant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientHistory> PatientHistories { get; set; }
    }
}
