//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedDb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientHistory
    {
        public int ID { get; set; }
        public int PatientFileID { get; set; }
        public int DiagnosticID { get; set; }
        public int TenantID { get; set; }
        public string EntryDescription { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Diagnostic Diagnostic { get; set; }
        public virtual PatientFile PatientFile { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
